site_name: Encrypted Team Docs
theme:
  name: material

plugins:
  - search
  
  - encryptcontent:
      global_password: !ENV DOCS_PASSWORD
      summary: "Please enter the password to access the documentation."
      title_prefix: ""
      search_index: "dynamically" 
      encryption_info_message: "Contact our team to get access."

  - multirepo:
      cleanup: true 

  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["child_repos/repo_a/src"]
          options:
            docstring_style: google

nav:
  - Home: index.md
  - Calculator Module: '!import https://github.com/captainvoldemort/mkdocs-cloudflare-host-trial-1?branch=main'
